# Generated by Django 3.1.3 on 2021-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud_Teach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
