# Generated by Django 3.1.3 on 2021-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud_Teach', '0002_auto_20210530_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], max_length=10),
        ),
    ]
