# Generated by Django 3.1.3 on 2021-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud_Teach', '0003_auto_20210530_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
