# Generated by Django 3.1.3 on 2021-06-02 06:16

import Stud_Teach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud_Teach', '0004_auto_20210530_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(upload_to=Stud_Teach.models.get_path_by_course_title),
        ),
    ]
