# Generated by Django 3.1.3 on 2021-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud_Teach', '0005_auto_20210602_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
